apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
        - name: student
          image: student-service:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8082

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s

          # âœ… ONLY LIVENESS (ENOUGH)
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 120
            periodSeconds: 20