apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deployment
  labels:
    app: student
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
        - name: student
          image: student-service:1.0
          imagePullPolicy: Always

          ports:
            - containerPort: 8082

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

          # ✅ READINESS: traffic only when DB + app is ready
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3

          # ✅ LIVENESS: restart only if app is truly dead
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 5
            timeoutSeconds: 3
